In [ ]:
import sys
sys.path.append('../modules')
from utils import *
from lonlat_to_healpix import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
dt = get_datatree('biscay', '2025-06-17')

Searching https://stac.core.eopf.eodc.eu for items in sentinel-3-slstr-l1-rbt collection
 on 2025-06-17 at lon=-4.5, lat=48.0...
Found 6 items
Opening the data tree for item no. 1:
 S3A_SL_1_RBT____20250617T213612_20250617T213912_20250619T085024_0179_127_129_0720_PS1_O_NT_004
Opened the data tree with 97 groups


## Subsets with lon/lat

In [ ]:
dt.conditions.meteorology # a datatree with lon/lat 

<xarray.DataTree 'meteorology'>
Group: /conditions/meteorology
    Dimensions:                       (rows: 1200, columns: 130, t_series: 5,
                                       p_atmos: 25)
    Coordinates:
      * t_series                      (t_series) datetime64[ns] 40B 2025-06-17T06...
      * p_atmos                       (p_atmos) float32 100B 1.0 2.0 ... 950.0 1e+03
        latitude                      (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        longitude                     (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    Dimensions without coordinates: rows, columns
    Data variables: (12/22)
        cloud_fraction_tp             (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        dew_point_tp                  (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        east_west_stress_tp           (t_series, rows, columns) float32 3MB dask.array<chunksize=(5, 1200, 130), meta=np.ndarray>
        latent_heat_tp                (t_series, rows, columns) float32 3MB dask.array<chunksize=(5, 1200, 130), meta=np.ndarray>
        north_south_stress_tp         (t_series, rows, columns) float32 3MB dask.array<chunksize=(5, 1200, 130), meta=np.ndarray>
        sea_ice_fraction_tp           (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        ...                            ...
        temperature_tp                (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        thermal_radiation_tp          (t_series, rows, columns) float32 3MB dask.array<chunksize=(5, 1200, 130), meta=np.ndarray>
        total_column_ozone_tp         (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        total_column_water_vapour_tp  (rows, columns) float32 624kB dask.array<chunksize=(1200, 130), meta=np.ndarray>
        u_wind_tp                     (t_series, rows, columns) float32 3MB dask.array<chunksize=(3, 1200, 130), meta=np.ndarray>
        v_wind_tp                     (t_series, rows, columns) float32 3MB dask.array<chunksize=(3, 1200, 130), meta=np.ndarray>

In [ ]:
da = dt.conditions.meteorology.sea_ice_fraction_tp
da # data array

<xarray.DataArray 'sea_ice_fraction_tp' (rows: 1200, columns: 130)> Size: 624kB
dask.array<open_dataset-sea_ice_fraction_tp, shape=(1200, 130), dtype=float32, chunksize=(1200, 130), chunktype=numpy.ndarray>
Coordinates:
    latitude   (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    longitude  (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
Dimensions without coordinates: rows, columns
Attributes: (6)

In [ ]:
da_hpx = add_healpix_to_dataarray(da, verbose=True)

Calculating pixel sizes...
PIXEL SIZE STATISTICS

Row-wise pixel sizes (North-South direction):
  Mean:   999.14 m
  Median: 1003.59 m
  Min:    972.61 m
  Max:    1009.50 m

Column-wise pixel sizes (East-West direction):
  Mean:   16000.02 m
  Median: 16000.02 m
  Min:    16000.00 m
  Max:    16000.06 m

Using pixel size: 16000.02 m (max of row/column)

Selected HEALPix level: 8
  Pixel size: 16000.02 m
  Edge length: 25467.43 m
  Ratio: 1.59x

Calculating HEALPix cell IDs at level 8...
Added HEALPix coordinates:
  Valid pixels: 156000 / 156000
  Unique cells: 3968
  Level: 8
  Grid mapping: crs (CF-compliant)


/home/kajetan/miniconda3/envs/healpix/lib/python3.13/site-packages/numpy/_core/numeric.py:387: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')


In [ ]:
da_hpx 

<xarray.DataArray 'sea_ice_fraction_tp' (rows: 1200, columns: 130)> Size: 624kB
dask.array<open_dataset-sea_ice_fraction_tp, shape=(1200, 130), dtype=float32, chunksize=(1200, 130), chunktype=numpy.ndarray>
Coordinates:
    latitude   (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    longitude  (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    healpix    (rows, columns) int64 1MB 44063 44062 44084 ... 226082 225911
    crs        int8 1B 0
Dimensions without coordinates: rows, columns
Attributes: (8)

In [ ]:
print_healpix_info(da_hpx)


Test DataArray with HEALPix coordinates:
  Coordinates: ['latitude', 'longitude', 'healpix', 'crs']
  HEALPix level: 8
  Indexing scheme: nested
  Reference body: WGS84

HEALPix cell IDs shape: (1200, 130)
Unique HEALPix cells: 3968

HEALPix cell IDs:
[[ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  44084 ... 218042 219397 219396]
 ...
 [ 47525  47526  47526 ... 226082 226082 225911]
 [ 47525  47526  47526 ... 226082 226082 225911]
 [ 47525  47527  47526 ... 226082 226082 225911]]

CRS metadata:
  grid_mapping_name: healpix
  refinement_level: 8
  indexing_scheme: nested
  reference_body: WGS84
  refinement_ratio: 4


In [ ]:
da2 = dt.conditions.meteorology.east_west_stress_tp
da2



<xarray.DataArray 'east_west_stress_tp' (t_series: 5, rows: 1200, columns: 130)> Size: 3MB
dask.array<open_dataset-east_west_stress_tp, shape=(5, 1200, 130), dtype=float32, chunksize=(5, 1200, 130), chunktype=numpy.ndarray>
Coordinates:
  * t_series   (t_series) datetime64[ns] 40B 2025-06-17T06:00:00 ... 2025-06-...
    latitude   (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    longitude  (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
Dimensions without coordinates: rows, columns
Attributes: (7)

In [ ]:
da2_hpx = add_healpix_to_dataarray(da2, verbose=True)

Calculating pixel sizes...
PIXEL SIZE STATISTICS

Row-wise pixel sizes (North-South direction):
  Mean:   999.14 m
  Median: 1003.59 m
  Min:    972.61 m
  Max:    1009.50 m

Column-wise pixel sizes (East-West direction):
  Mean:   16000.02 m
  Median: 16000.02 m
  Min:    16000.00 m
  Max:    16000.06 m

Using pixel size: 16000.02 m (max of row/column)

Selected HEALPix level: 8
  Pixel size: 16000.02 m
  Edge length: 25467.43 m
  Ratio: 1.59x

Calculating HEALPix cell IDs at level 8...
Added HEALPix coordinates:
  Valid pixels: 156000 / 156000
  Unique cells: 3968
  Level: 8
  Grid mapping: crs (CF-compliant)

Test DataArray with HEALPix coordinates:
  Coordinates: ['latitude', 'longitude', 't_series', 'healpix', 'crs']
  HEALPix level: 8
  Indexing scheme: nested
  Reference body: WGS84

HEALPix cell IDs shape: (1200, 130)
Unique HEALPix cells: 3968

HEALPix cell IDs:
[[ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  4

/home/kajetan/miniconda3/envs/healpix/lib/python3.13/site-packages/numpy/_core/numeric.py:387: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')


In [ ]:
da2_hpx

<xarray.DataArray 'east_west_stress_tp' (t_series: 5, rows: 1200, columns: 130)> Size: 3MB
dask.array<open_dataset-east_west_stress_tp, shape=(5, 1200, 130), dtype=float32, chunksize=(5, 1200, 130), chunktype=numpy.ndarray>
Coordinates:
  * t_series   (t_series) datetime64[ns] 40B 2025-06-17T06:00:00 ... 2025-06-...
    latitude   (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    longitude  (rows, columns) float64 1MB dask.array<chunksize=(1200, 130), meta=np.ndarray>
    healpix    (rows, columns) int64 1MB 44063 44062 44084 ... 226082 225911
    crs        int8 1B 0
Dimensions without coordinates: rows, columns
Attributes: (9)

In [ ]:
print_healpix_info(da2_hpx)


Test DataArray with HEALPix coordinates:
  Coordinates: ['latitude', 'longitude', 't_series', 'healpix', 'crs']
  HEALPix level: 8
  Indexing scheme: nested
  Reference body: WGS84

HEALPix cell IDs shape: (1200, 130)
Unique HEALPix cells: 3968

HEALPix cell IDs:
[[ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  44084 ... 218042 218031 219396]
 [ 44063  44062  44084 ... 218042 219397 219396]
 ...
 [ 47525  47526  47526 ... 226082 226082 225911]
 [ 47525  47526  47526 ... 226082 226082 225911]
 [ 47525  47527  47526 ... 226082 226082 225911]]

CRS metadata:
  grid_mapping_name: healpix
  refinement_level: 8
  indexing_scheme: nested
  reference_body: WGS84
  refinement_ratio: 4
